trigger:
    - main

pool:
    vmImage: ubuntu-latest

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "16.x"
      displayName: "Install Node.js"

    - script: |
          npm install
      displayName: "npm install dependencies"

    - script: |
          npm run build
      displayName: "npm build"

    - script: |
          node .\greasemonkey\patchVersion.js ${{variables['Build.SourceBranchName']}}
      displayName: "Patch version tag in release files"
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))

    - task: PublishBuildArtifacts@1
      inputs:
          PathtoPublish: "dist"
          ArtifactName: "GCComment 2 Tampermonkey script"
          publishLocation: "Container"
      displayName: "Publish build script"
