export const AUTOMOVEMYSTERIESBETA = "autoMoveMysteriesbeta";
export const AUTOMOVEMYSTERIESBETAFOUND = "autoMoveMysteriesbetafound";
export const AUTOMOVEMYSTERIESBETASOLVED = "autoMoveMysteriesbetasolved";
export const AUTOMOVEMYSTERIESBETAHOME = "autoMoveMysteriesbetahome";
export const AUTOMOVEMYSTERIESBETAAREA = "autoMoveMysteriesbetaarea";
export const AUTOMOVEMYSTERIESBETAUNSOLVED = "autoMoveMysteriesbetaunsolved";
export const AUTOMOVEMYSTERIESBETAINCLUDEWPT =
    "autoMoveMysteriesbetaIncludeWaypoints";
export const ADDCOMMENTSETTING = "addCommentSetting";
export const CHANGEORIGINALSETTING = "changeOriginalSetting";
export const ADDWAYPOINTSETTING = "addWaypointSetting";
export const PATCHGPX_CHANGEORIGINAL = "patchGPXChangeOriginal";
export const PATCHGPX_ADDFINALWPT = "patchGPXAddFinalWpt";
export const ENABLE_EXPORT = "enableExport";
export const PATCHGPX_REMOVE_DEFAULTTYPE = "PATCHGPX_REMOVE_DEFAULTTYPE";
export const PATCHGPX_REMOVE_SOLVED = "PATCHGPX_REMOVE_SOLVED";
export const PATCHGPX_REMOVE_UNSOLVED = "PATCHGPX_REMOVE_UNSOLVED";
export const PATCHGPX_REMOVE_FOUND = "PATCHGPX_REMOVE_FOUND";
export const PATCHGPX_REMOVE_OTHERS = "PATCHGPX_REMOVE_OTHERS";
export const PATCHGPX_STRIP_EMOJIS = "PATCHGPX_STRIP_EMOJIS";
export const PATCHGPX_STRIP_HTML_TAGS = "PATCHGPX_STRIP_HTML_TAGS";
export const UNTYPED_FILTER_ALL = "UNTYPED_FILTER_ALL";
export const UNTYPED_FILTER_UNTYPED = "UNTYPED_FILTER_UNTYPED";
export const UNTYPED_FILTER_UNSOLVED = "UNTYPED_FILTER_UNSOLVED";
export const UNTYPED_FILTER_SOLVED = "UNTYPED_FILTER_SOLVED";
export const UNTYPED_FILTER_FOUND = "UNTYPED_FILTER_FOUND";
export const UNTYPED_FILTER_ARCHIVED = "UNTYPED_FILTER_ARCHIVED";
export const UNTYPED_FILTER_ARCHIVED_BOTH = "UNTYPED_FILTER_ARCHIVED_BOTH";
export const UNTYPED_FILTER_ARCHIVED_ARCHIVED =
    "UNTYPED_FILTER_ARCHIVED_ARCHIVED";
export const UNTYPED_FILTER_ARCHIVED_NOT_ARCHIVED =
    "UNTYPED_FILTER_ARCHIVED_NOT_ARCHIVED";
export const FILTER_TYPE_EXPORT = "FILTER_TYPE_EXPORT";
export const FILTER_TYPE_DELETE = "FILTER_TYPE_DELETE";
export const EXPORT_FILTER_ALL = "EXPORT_FILTER_ALL";
export const EXPORT_FILTER_UNTYPED = "EXPORT_FILTER_UNTYPED";
export const EXPORT_FILTER_UNSOLVED = "EXPORT_FILTER_UNSOLVED";
export const EXPORT_FILTER_SOLVED = "EXPORT_FILTER_SOLVED";
export const EXPORT_FILTER_FOUND = "EXPORT_FILTER_FOUND";
export const EXPORT_FILTER_ARCHIVED = "EXPORT_FILTER_ARCHIVED";
export const EXPORT_FILTER_ARCHIVED_BOTH = "EXPORT_FILTER_ARCHIVED_BOTH";
export const EXPORT_FILTER_ARCHIVED_ARCHIVED =
    "EXPORT_FILTER_ARCHIVED_ARCHIVED";
export const EXPORT_FILTER_ARCHIVED_NOT_ARCHIVED =
    "EXPORT_FILTER_ARCHIVED_NOT_ARCHIVED";
export const DELETEALL_FILTER_ALL = "DELETEALL_FILTER_ALL";
export const DELETEALL_FILTER_UNTYPED = "DELETEALL_FILTER_UNTYPED";
export const DELETEALL_FILTER_UNSOLVED = "DELETEALL_FILTER_UNSOLVED";
export const DELETEALL_FILTER_SOLVED = "DELETEALL_FILTER_SOLVED";
export const DELETEALL_FILTER_FOUND = "DELETEALL_FILTER_FOUND";
export const DELETEALL_FILTER_ARCHIVED = "DELETEALL_FILTER_ARCHIVED";
export const DELETEALL_FILTER_ARCHIVED_BOTH = "DELETEALL_FILTER_ARCHIVED_BOTH";
export const DELETEALL_FILTER_ARCHIVED_ARCHIVED =
    "DELETEALL_FILTER_ARCHIVED_ARCHIVED";
export const DELETEALL_FILTER_ARCHIVED_NOT_ARCHIVED =
    "DELETEALL_FILTER_ARCHIVED_NOT_ARCHIVED";
export const LAZY_TABLE_REFRESH = "lazytablerefresh";
export const AUTO_UPDATE_GS_FINAL = "autoupdategsfinal";
export const AUTO_UPLOAD_CACHE_NOTES = "autoupdatecachenotes";
export const AUTOMARKFOUND = "automarkfound";
export const AUTOMARKARCHIVE = "automarkarchive";
export const SETTINGS_LANGUAGE = "settings language";
export const SETTINGS_LANGUAGE_EN = "English";
export const SETTINGS_LANGUAGE_DE = "Deutsch";
export const SETTINGS_LANGUAGE_AUTO = "Auto";
export const SETTING_ARCHIVE_FILTER = "SETTING_ARCHIVE_FILTER";
export const ARCHIVE_FILTER_NO_ARCHIVED = "ARCHIVE_FILTER_NO_ARCHIVED";
export const ARCHIVE_FILTER_INCLUDE_ARCHIVED =
    "ARCHIVE_FILTER_INCLUDE_ARCHIVED";
export const ARCHIVE_FILTER_ONLY_ARCHIVED = "ARCHIVE_FILTER_ONLY_ARCHIVED";
